# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 4 versions"
  - "ie >= 9"
  - "and_chr >= 2.3"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - "src/**/*.html"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"  
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    # "src/assets/**/**/*"
    - "src/assets/docs/**/*"
    - "src/assets/**/vendor/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "bower_components/foundation-sites/scss"
    - "bower_components/motion-ui/src"
  # Paths to JavaScript libraries, which are compined into one file
  sasshome:
    - "bower_components/foundation-sites/scss"
  # Paths to JavaScript libraries, which are compined into one file
  javascriptcorp:
    # Libraries requried by Foundation
    #- "bower_components/jquery/dist/jquery.js"
    - "bower_components/what-input/dist/what-input.js"
    # Core Foundation files
    - "bower_components/foundation-sites/js/foundation.core.js"
    - "bower_components/foundation-sites/js/foundation.util.*.js"
    # Individual Foundation components
    # If you aren't using a component, just remove it from the list
    - "bower_components/foundation-sites/js/foundation.abide.js"
    - "bower_components/foundation-sites/js/foundation.accordion.js"
    - "bower_components/foundation-sites/js/foundation.accordionMenu.js"
    # "bower_components/foundation-sites/js/foundation.drilldown.js"
    # "bower_components/foundation-sites/js/foundation.dropdown.js"
    # "bower_components/foundation-sites/js/foundation.dropdownMenu.js"
    - "bower_components/foundation-sites/js/foundation.equalizer.js"
    # "bower_components/foundation-sites/js/foundation.interchange.js"
    # "bower_components/foundation-sites/js/foundation.magellan.js"
    # "bower_components/foundation-sites/js/foundation.offcanvas.js"
    - "bower_components/foundation-sites/js/foundation.orbit.js"
    # "bower_components/foundation-sites/js/foundation.responsiveMenu.js"
    # "bower_components/foundation-sites/js/foundation.responsiveToggle.js"
    - "bower_components/foundation-sites/js/foundation.reveal.js"
    # "bower_components/foundation-sites/js/foundation.slider.js"
    # "bower_components/foundation-sites/js/foundation.sticky.js"
    - "bower_components/foundation-sites/js/foundation.tabs.js"
    - "bower_components/foundation-sites/js/foundation.toggler.js"
    - "bower_components/foundation-sites/js/foundation.tooltip.js"
    # "bower_components/foundation-sites/js/foundation.zf.responsiveAccordionTabs.js"
    # Paths to your own project code are here   
    - "src/assets/js/fmGlobals.js"
    - "src/assets/js/headerNav_corp.js"
    - "src/assets/js/adjustSidebar.js"
    - "src/assets/js/prepModals.js"
    - "src/assets/js/prepRotators.js" 
    # comment for prod code. this is just for local site
    # "src/assets/js/fakeNav_corp.js"  
    - "src/assets/js/mwNewsFeed.js"
    - "src/assets/js/tertiaryNav_corp.js"   
    - "src/assets/js/appCorp.js"
    #uncomment for prod if desired 
    - "src/assets/js/shareWidget.js"
    # Paths to JavaScript libraries, which are compined into one file
  javascriptsf:
    # Libraries requried by Foundation
    #- "bower_components/jquery/dist/jquery.js"
    - "bower_components/what-input/dist/what-input.js"
    # Core Foundation files
    - "bower_components/foundation-sites/js/foundation.core.js"
    - "bower_components/foundation-sites/js/foundation.util.*.js"
  javascriptmf:
    # Libraries requried by Foundation
    #- "bower_components/jquery/dist/jquery.js"
    - "bower_components/what-input/dist/what-input.js"
    # Core Foundation files
    - "bower_components/foundation-sites/js/foundation.core.js"
    - "bower_components/foundation-sites/js/foundation.util.*.js"
  javascriptmfsbl:
    # Libraries requried by Foundation
    #- "bower_components/jquery/dist/jquery.js"
    - "bower_components/what-input/dist/what-input.js"
    # Core Foundation files
    - "bower_components/foundation-sites/js/foundation.core.js"
    - "bower_components/foundation-sites/js/foundation.util.*.js"
    # Individual Foundation components
    # If you aren't using a component, just remove it from the list
    - "bower_components/foundation-sites/js/foundation.abide.js"
    - "bower_components/foundation-sites/js/foundation.accordion.js"
    # "bower_components/foundation-sites/js/foundation.accordionMenu.js"
    # "bower_components/foundation-sites/js/foundation.drilldown.js"
    # "bower_components/foundation-sites/js/foundation.dropdownMenu.js"
    - "bower_components/foundation-sites/js/foundation.equalizer.js"
    # "bower_components/foundation-sites/js/foundation.interchange.js"
    # "bower_components/foundation-sites/js/foundation.magellan.js"
    # "bower_components/foundation-sites/js/foundation.offcanvas.js"
    - "bower_components/foundation-sites/js/foundation.orbit.js"
    # "bower_components/foundation-sites/js/foundation.responsiveMenu.js"
    # "bower_components/foundation-sites/js/foundation.responsiveToggle.js"
    - "bower_components/foundation-sites/js/foundation.reveal.js"
    # "bower_components/foundation-sites/js/foundation.slider.js"
    # "bower_components/foundation-sites/js/foundation.sticky.js"
    # "bower_components/foundation-sites/js/foundation.tabs.js"
    - "bower_components/foundation-sites/js/foundation.toggler.js"
    - "bower_components/foundation-sites/js/foundation.tooltip.js"
    # "bower_components/foundation-sites/js/foundation.zf.responsiveAccordionTabs.js"
    - "bower_components/foundation-sites/js/foundation.dropdown.js"
    # Paths to your own project code are here   
    - "src/assets/js/fmGlobals.js"
    - "src/assets/js/prepModals.js"
    # "src/assets/js/prepRotators.js"   
    - "src/assets/js/appMf-sbl.js"
    # Individual Foundation components
  javascriptcm:
    # Libraries requried by Foundation
    #- "bower_components/jquery/dist/jquery.js"
    - "bower_components/what-input/dist/what-input.js"
    # Core Foundation files
    - "bower_components/foundation-sites/js/foundation.core.js"
    - "bower_components/foundation-sites/js/foundation.util.*.js"

